language: node_js
node_js:
- '9'
- '10'
cache:
  yarn: true
  directories:
  - node_modules
  - "$HOME/.npm"
install: yarn
script:
- yarn prettier
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
env:
  global:
    secure: aOvz7hbApfVzR7WJSfbKWmtZWLFw5yre2ilfrYLJaDR9oGQTAYtbU/VDMOthWFd5hdXfPN16Iwh0nnMoQqOi4Mgpk5D17y2FdeHcxhOlYAtb0c9R4Lykm6e7FR1JTMYCc/m/qWR7FKYlVBHSgCPUBWnldI20QFHVRDnHygL371zM9xh9HMpaNmd69+lv2ql2QcCBYMITvriyivO0PtsEUbgMOg7tMysP95QyMkXowoXRjygxXM75KF/n2SSlS4So4hYXNx1OjpUl6BrPNw6IXRSOxBLSVBGYSdR33o6jQ/7gBCRoIqEDYFEurF9O3lNReG3uZQ/e9uRoc6NUMdONbTrkuqXkpNYC4Eum1bKP4Vbah37rhdZzBkYPxs9x+17fwNB249H+ftBKOvAsCFa5wophbD5PIWvmygogaZ3NkqCNWESlo3P9VD3Y6Y/k4A2/ZP08bu7B49ZUzGK3uGpzO/bbPmnGfvMGnQxg+g2gP7XX5tHz11/6F1f8JDHyQYzIzQDWHKBIrFpSH1/fV3SmcoBwIg9MlUwRJoeP0xYDvJ9GRDmWBrBOlATpU4BPiuaQOiMQydqu+K6Z4afNsnU/1HFwXLNEiq9Ob2Rmx8BmsTU2+aZt9roRJnl+XtQy7fry3umspSGUQHGOjpvEbDVH9bHAngVQtFH9uUq2jlc68Mo=
deploy:
  provider: npm
  email: andyfang.dz@gmail.com
  api_key:
    secure: awo8Vld04mEX9F7OpCxCq6aMSa914RXhyXZVzVla8UcShNdGHnPZIzgBrxDv19DQAkjo6j+sVReE/YWa4zGkHbaGMrFb6oO+AApaoohCPyVakUp+St33unrlSu8MePgSyNSWu8Eeb++kEScynBDV1YlzN8G6WjzjXHkdnKu6zde+SO3XAMcFIAMABt0V5RadGGog41cm6aqZPWt/knh/IIZUpmJL7sxAD9sqOkM/dfufxs4KPWSasUeecBJ0aofgHIPA7MDKXjl9brBiSE/+r5q2+32nBEFHWW0f1XpE32qDwiKXxrFjAmCYwB7G2ilznCk9U4cB7mW/D9L+Kh5EQwMwU6y0hpToGlsk1iUIHmHGpT6nX3YQby8vRUc93ggq9qNDmKT+KRLMPArM3YHmvk/8io6LgIWlNcYlYReGlbBU811rLMwFg/8iBkkK6ej6dJ62VP+w44ymrk1j6WHdfRNUanO+ywpf/EUuCbwWd1RzL3HcpTbpVIR0hYPeQmb/2virTSQH9RVhKQ11ECyGUKbCe4h7KnFykVDwoCsX3Voo/Uxb/1AWDzoZR42P/0cZve16/Vx7FW0x7Xg1z2x81WHf2hYkp8X+iWNOxsCaqT0qkQUpit13iLB3THPhZYB8yVG7HhxerAKXGXfBihVoXpBNOPDSHoYQP0/EfXBOdFI=
  on:
    tags: true
    repo: andyfangdz/prettierrc
