language: node_js
node_js:
- '9'
- '10'
cache:
  yarn: true
  directories:
  - node_modules
  - "$HOME/.npm"
install: yarn
script:
- yarn prettier
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: andyfang.dz@gmail.com
  api_key:
    secure: "lPcTMp057Ja6iuZ8YrFfMXPiXyc6et9l7wpINHZbM58hPIHuOBRJE3+GdH7rTF0Qbazjw04YanK/EPwXL0tIfbL+2BM0PYhZNxk5BZpcpCKjv4V7oEzMQyfR1BmbmVHgoAhzyIY/65Yea1YXp0nxiE7Vksy/usvZHmbPXzw+2HG6huLmPqkQRt3A9JfQa//4C8fIkBPwlZfMFhACov4EaPK+zMc+wHaFXx46JQ38wc2y+SLYhyGHvKIZYD1dUo2ZFD046aGUoNNRGKbGZkbPFRwLaVjsGL4XuNnXbX+AGJSPIEaXusGMzX0092J4y8rUbvqDJ6JynQ/EAdoWtjQFgK085NGOSSo/ez2lLmYL8jdohj/hNa7WTl1yhmq66U2ya1du/w/fmA2Ukh/mycVUUuyRN6+iGimuHgy0iW2cB+OO3TNK2qqCEZ/G46SEUf658aZbvUa8fcKvjIN2l/0p3/dQTpoK6M/Mm7Okz5TGj3qdOGiWowPAtzgITGCoz08F8/HHDPRoviiRsXm4F0xUKoJEhEODsPp3GJOqIpmG2LpvK+HzJj+2oHsDFA3M7P5BruMAk8+Klkyge6OiMu3QRLX59XFnkIquZWAu0x69ew0g3xqEeci121wfuPeCJ+ZOktsZngzE+GrfaJ6ioVd0K/AHRIlZF9diOZrNlpftmyA="
  on:
    tags: true
    repo: andyfangdz/prettierrc
